### ISSUE TITLE
Erroneous mapping on com.recurly.v3.resources.SubscriptionRampIntervalResponse.unitAmount field causes NumberFormatException 

### ISSUE THREAD

**Issue by jlrvilla** [recurly/recurly-client-java#214]
**Describe the bug**

Whenever you try to interact with a subscription that relates to a plan with ramp interval pricing with float values the library its failing with an exception like:

```[...] nested exception is com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 12.5 at line 1 column 1145 path $.ramp_intervals[0].unit_amount [...]```

I guess the problem roots to the fact that there is type discrepancy between [SubscriptionRampIntervalResponse.unitAmount](https://github.com/recurly/recurly-client-java/blob/v3-v2021-02-25/src/main/java/com/recurly/v3/resources/SubscriptionRampIntervalResponse.java#L27) and [PlanRampPricing.unitAmount](https://github.com/recurly/recurly-client-java/blob/v3-v2021-02-25/src/main/java/com/recurly/v3/resources/PlanRampPricing.java#L23)

**To Reproduce**

1. Create a plan with ramp intervals with decimal values (e.g. 12.5)
2. Create a subscription for the plan created in step 1
3. Try to retrieve the information related to the subscription created in step 2

**Expected behavior**

To properly map the ramp pricing on subscription object.

**Your Environment**

- Which version of this library are you using? 4.23.0
- Which version of the language are you using? Java 17

**Comment by mwlang** [comment]
@jlrvilla thank you for reporting this bug and steps to reproduce.  We will take a look at this and get back to you over the next few days.  Let us know if you're intending to also submit a pull request as we'll gladly work with you to accept.

**Comment by mwlang** [comment]
NOTE:  This issue doesn't look fixable with a pull-request given the auto-generated nature of the code from open-api specs.  Reviewing deeper to find where the discrepancy in creeping in.

**Comment by douglasmiller** [comment]
@jlrvilla we have corrected this issue in the referenced pull request and published version 4.24.1 of the client with the fix.

Thanks again for letting us know!

**Comment by jlrvilla** [comment]
Thanks!
