### ISSUE TITLE
Purchase preview

### ISSUE THREAD

**Issue by muratovi** [recurly/recurly-client-java#54]
Does java client support purchase preview endpoint ? 
If so how it should be created, if no - are there any plans to implement it?

**Comment by bhelx** [comment]
@muratovi I assume you found your answer, but yes we do support it with the method `Client#previewPurchase`: https://github.com/recurly/recurly-client-java/blob/798ed5a6b2e0a60d1e405e35e3042c2b8be5d243/src/main/java/com/recurly/v3/Client.java#L1781

It does seem we are missing the example code in our docs, we will get that fixed: https://developers.recurly.com/api/v2019-10-10/index.html#operation/preview_purchase

**Comment by muratovi** [comment]
> @muratovi I assume you found your answer, but yes we do support it with the method `Client#previewPurchase`:
> 
> https://github.com/recurly/recurly-client-java/blob/798ed5a6b2e0a60d1e405e35e3042c2b8be5d243/src/main/java/com/recurly/v3/Client.java#L1781
> 
> It does seem we are missing the example code in our docs, we will get that fixed: https://developers.recurly.com/api/v2019-10-10/index.html#operation/preview_purchase

Yes, I was confused by absence of example in code and was expecting to find `PurchasePreview` class (to be consistent with other names Purchase->PurchaseCreate). 

What about subscriptions preview, is it available in new API?
https://dev.recurly.com/docs/preview-subscription
