### ISSUE TITLE
Descriptive ApiError for purchase preview enpoint

### ISSUE THREAD

**Issue by muratovi** [recurly/recurly-client-java#57]
Not sure whether it's relevant after https://github.com/recurly/recurly-client-java/issues/55 was resolved, but if billing information has state (not configured in avalara) and zip code for state that is configured in avalara following error is thrown by API: 
<img width="504" alt="Screen Shot 2019-12-30 at 16 37 48" src="https://user-images.githubusercontent.com/23436091/71601767-e7704b00-2b22-11ea-972c-9eeb7fabc30c.png">

**Comment by bhelx** [comment]
I'd actually expect that to be a `ValidationException` and not a generic `ApiError`. What are the details in the `error` property?

**Comment by muratovi** [comment]
> I'd actually expect that to be a `ValidationException` and not a generic `ApiError`. What are the details in the `error` property?

It returns "Tax service currently not available, please try again later." 
But in reality service is available, but provided billing information is intentionally incorrect (NY as state and NJ as zip code)

<img width="521" alt="Screen Shot 2019-12-31 at 12 41 23" src="https://user-images.githubusercontent.com/23436091/71629335-eabf1180-2bca-11ea-8226-d8fa43a65d82.png">

**Comment by bhelx** [comment]
Okay, thanks for providing the details. Let me see what is happening on the API side. I'd expect the server to be doing something different.

**Comment by bhelx** [comment]
@muratovi It appears that the API is not properly distinguishing b/w different error categories from our tax service. I'm going to file a ticket to investigate this and perhaps get a fix out. We should only be throwing that "service_not_available" error in the event that the service is actually down.

**Comment by muratovi** [comment]
@bhelx Can you include `Error` object into exception message and review logic on how `message` and `params` fields are populated ?   
```  
public ApiException(String message, Error e) {
    super(message);
    this.error = e;
  }
```
In some exceptions only `message` or `params` field is populated, that complicates usage of API:  
<img width="390" alt="Screen Shot 2020-01-13 at 16 48 54" src="https://user-images.githubusercontent.com/23436091/72295197-0a235900-3625-11ea-8cbe-47f91736f9ff.png">

**Comment by bhelx** [comment]
I believe this has been addressed. Feel free to re-open or continue the discussion if not.
