### ISSUE TITLE
transaction_error is hidden from ApiException when a transaction fails

### ISSUE THREAD

**Issue by zhuravskiy** [recurly/recurly-client-java#58]
**Describe the bug**

When purchase fails backend returns response like this:

```
{
  "error": {
    "type": "transaction",
    "message": "Your transaction was declined. Please contact your bank for further details or try another card.",
    "transaction_error": {
      "object": "transaction_error",
      "transaction_id": "mbca9aaao6xr",
      "category": "hard",
      "code": "invalid_payment_method_hard",
      "message": "Your transaction was declined. Please contact your bank for further details or try another card.",
      "merchant_advice": "The transaction was declined by the payment gateway. Contact the payment gateway for more details.",
      "three_d_secure_action_token_id": null
    }
  }
}
```
`transaction_error` nested object is important to get details about whats going on, but with following implementation not possible to get this.

https://github.com/recurly/recurly-client-java/blob/master/src/main/java/com/recurly/v3/JsonSerializer.java#L31

https://github.com/recurly/recurly-client-java/blob/master/src/main/java/com/recurly/v3/resources/Error.java only have common fileds, but not `transaction_error`.

**Your Environment**

lib version 3.2.0

Please improve this. 

Looks like #55 and #57 is related.

Update: https://github.com/recurly/recurly-client-java/blob/d3fa85d549ddd81082619753fc7b292365ef7d44/src/main/java/com/recurly/v3/resources/ErrorMayHaveTransaction.java cant find usages.

**Comment by bhelx** [comment]
Thanks for reporting @zhuravskiy . I was just about to fix this but you beat me to it! You've edited a few auto-generated files but we will upstream those changes into the generator for you.

**Comment by zhuravskiy** [comment]
@bhelx thank you!

**Comment by bhelx** [comment]
This has been released in https://github.com/recurly/recurly-client-java/releases/tag/3.3.0
It's headed through the nexus pipeline and will be arriving in maven central soon. Let us know if the fix isn't working for any reason.
