### ISSUE TITLE
Do you have plans to support (credit invoices) in the V3 API ?

### ISSUE THREAD

**Issue by zhuravskiy** [recurly/recurly-client-java#68]
Hello guys!
I do not see the ability to create a credit invoice or adjustments like it was in the V2 https://dev.recurly.com/docs/create-a-credit

do you have it in the roadmap for v3?

thank you

**Comment by bhelx** [comment]
@zhuravskiy See the docs for `create_line_item` https://developers.recurly.com/api/v2019-10-10/index.html#operation/create_line_item

You can use `type=credit` in that request.

**Comment by zhuravskiy** [comment]
question closed! @bhelx thank you!
