### ISSUE TITLE
Documentation has not all invoice states

### ISSUE THREAD

**Issue by zhuravskiy** [recurly/recurly-client-java#69]
**Describe the bug**

Documentation has a bug related

```
 (Invoice state)
Enum: "pending" "processing" "past_due" "paid" "failed"
```
missed `open` and `closed` values related to credit invoices, maybe some other states too.

**To Reproduce**

Create a credit invoice or void a credit invoice.

**Comment by bhelx** [comment]
Thanks, I am looking into it. I actually think the names have changed and this represent the old names. `pending => open` and `paid => closed`. I also think we may be missing `voided`. I'll report back with what I've found.

**Comment by bhelx** [comment]
@zhuravskiy I have identified this as a documentation mistake and we're fixing it for all the versions. The docs site will be updated next week and the inline docs will be updated next time we generate the clients. In the meantime, this is the actual list:

* open
* processing
* past_due
* closed
* failed
* voided

As stated in the above comment, `pending` is now `open` and `paid` is now `closed`.

**Comment by zhuravskiy** [comment]
@bhelx thank you! very helpful!

**Comment by bhelx** [comment]
Thank you again! We appreciate you taking the time to contribute.
